config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
             controller: "clearance/passwords",
             only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  namespace :admin do
    resources :rarities
    resources :kiths
    resources :seemings
    resources :animal_seemings
    resources :phyla
    resources :houses
    resources :bannerhouses
    resources :courts
    resources :seelie_legacies
    resources :unseelie_legacies
    resources :genders
    resources :thallain_kiths

    root to: "rarities#index"
  end

  get 'kithain', to: 'kithain#index', as: 'kithain'
  get 'kithain/new', to: 'kithain#new', as: 'new_kithain'
  post 'kithain/regenerate', to: 'kithain#regenerate', as: 'regenerate_kithain'

  get 'thallain', to: 'thallain#index', as: 'thallain'
  get 'thallain/new', to: 'thallain#new', as: 'new_thallain'
  post 'thallain/regenerate', to: 'thallain#regenerate', as: 'regenerate_thallain'

  root 'kithain#index'
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/views/users/new.html.haml
#clearance.sign-up
  .card.card-bordered.w-full.max-w-xl.bg-base-300.shadow-xl.mx-auto
    .card-body
      %h1.card-title= t(".title")
      = form_for @user, html: { class: 'grid gap-3' } do |form|
        .form-control.w-full.max-w-lg.grid.grid-cols-4
          = form.label :email, class: 'label col-span-4 md:col-span-1 pt-0 md:pt-2'
          = form.text_field :email, type: 'email', placeholder: 'Email',
            class: 'col-span-3 input input-bordered'
        .form-control.w-full.max-w-lg.grid.grid-cols-4
          = form.label :password, class: 'label'
          = form.password_field :password, placeholder: 'Password',
            class: 'col-span-4 md:col-span-3 select select-bordered'
        .form-control.w-full.max-w-lg
          = form.submit class: 'btn btn-primary'
        .other-links
          = link_to t(".sign_in"), sign_in_path